import pickle
import numpy as np
import os
from Join_scheme.binning import apply_binning_to_data_value_count
from Join_scheme.factor import Factor


def load_sample_imdb(table_buckets, tables_alias, query_file_orders, join_keys, table_key_equivalent_group,
                     SPERCENTAGE=1.0, qdir="/home/ubuntu/data_CE/saved_models/binned_cards/{}/job/all_job/"):
    qdir = qdir.format(SPERCENTAGE)
    all_sample_factors = []
    for fn in query_file_orders:
        conditional_factors = load_sample_imdb_one_query(table_buckets, tables_alias, fn, join_keys,
                                                         table_key_equivalent_group, SPERCENTAGE, qdir)
        all_sample_factors.append(conditional_factors)
    return all_sample_factors


def _get_pdf_for_key(key, source_pdfs, gt_factor, table_name, table_buckets):
    """Get 1D raw count array for a key from source_pdfs or ground truth"""
    if source_pdfs is not None and key in source_pdfs:
        return source_pdfs[key]  # Already raw counts
    # gt_factor.pdfs are normalized probabilities; multiply by table_len to get raw counts
    if isinstance(gt_factor.pdfs, dict) and key in gt_factor.pdfs:
        return gt_factor.pdfs[key] * gt_factor.table_len
    n_bins = table_buckets[table_name].bin_sizes.get(key, 1)
    return np.ones(n_bins)


def load_sample_imdb_one_query(table_buckets, tables_alias, query_file_name, join_keys, table_key_equivalent_group,
                               SPERCENTAGE=1.0, qdir="/home/ubuntu/data_CE/saved_models/binned_cards/{}/job/all_job/"):
    qdir = qdir.format(SPERCENTAGE)
    fpath = os.path.join(qdir, query_file_name)
    with open(fpath, "rb") as f:
        data = pickle.load(f)

    # all_aliases in pkl use main query aliases (e.g., ci, t),
    # while the passed tables_alias uses current subquery aliases (e.g., cast_info1, title1).
    # The two alias systems differ; must use table name as intermediate key for matching.
    # alias_to_table: main query alias -> table name (saved during materialization, e.g., {ci: cast_info, t: title})
    # tables_alias:   subquery alias -> table name (generated by parse_query_simple during evaluation, e.g., {title1: title})
    alias_to_table = data.get("alias_to_table", {})
    if not alias_to_table:
        raise RuntimeError(
            f"pkl {query_file_name} is missing alias_to_table field, please re-run run_materialize_jobm.py"
        )
    # Reverse mapping of table_name -> subquery_alias in the subquery
    table_to_subquery_alias = {v: k for k, v in tables_alias.items()}

    # First pass: build 1D pdf for each (subquery_alias, key)
    source_pdfs = dict()   # subquery_alias -> {key -> 1D pdf array}
    filter_size = dict()   # subquery_alias -> filter_count

    for i, alias in enumerate(data["all_aliases"]):
        cards = data["results"][i][0]
        if cards is None:
            continue
        column = data["all_columns"][i]
        alias = alias[0]
        # Convert main query alias to table name
        table_name = alias_to_table.get(alias)
        if table_name is None:
            raise KeyError(f"Main query alias {alias!r} not found in alias_to_table: {alias_to_table}")
        # Find this table's alias in the current subquery; subquery is a subset of main query, tables not included are skipped normally
        subquery_alias = table_to_subquery_alias.get(table_name)
        if subquery_alias is None:
            continue
        key = table_name + "." + column
        if table_name not in table_buckets:
            raise KeyError(f"Table {table_name!r} not found in table_buckets")
        if key not in table_buckets[table_name].bin_sizes:
            raise KeyError(f"Key {key!r} not found in table_buckets[{table_name!r}].bin_sizes")
        n_bins = table_buckets[table_name].bin_sizes[key]
        pdfs = np.zeros(n_bins)
        for (j, val) in cards:
            if j is None:
                j = 0
            pdfs[j] += val
        table_len = np.sum(pdfs)
        if table_len == 0:
            # Empty sample means very little data after filtering; conservatively set filter_size=1 (consistent with sample_on_the_fly.py).
            # pdfs use gt normalized probability * 1 = tiny raw counts, dimensionally consistent with table_len.
            gt = table_key_equivalent_group[table_name]
            table_len = 1
            pdfs = gt.pdfs[key]  # Normalized probability, sum≈1, as tiny raw counts
        # Keep as raw counts, do not normalize
        if subquery_alias not in source_pdfs:
            source_pdfs[subquery_alias] = dict()
            filter_size[subquery_alias] = table_len
        source_pdfs[subquery_alias][key] = pdfs

    # Second pass: create Factor for each subquery table (pdfs as numpy array, 1D or 2D)
    conditional_factors = dict()
    for alias in tables_alias:
        table_name = tables_alias[alias]
        gt_factor = table_key_equivalent_group[table_name]

        if alias in source_pdfs:
            fs = filter_size[alias]
            table_len = min(gt_factor.table_len, fs / (SPERCENTAGE / 100))
            na_values = gt_factor.na_values
            sp = source_pdfs[alias]
        else:
            fs = gt_factor.table_len
            table_len = gt_factor.table_len
            na_values = gt_factor.na_values
            sp = None

        # Join keys this table participates in for the current subquery (expressed as real_table.column), sorted for determinism
        alias_keys = sorted(join_keys.get(alias, set()))

        if len(alias_keys) == 0:
            # No join key, fall back to ground truth
            conditional_factors[alias] = gt_factor
        elif len(alias_keys) == 1:
            key = alias_keys[0]
            # pdf_1d is raw counts (dimensionally consistent with oned_bin_modes)
            pdf_1d = _get_pdf_for_key(key, sp, gt_factor, table_name, table_buckets)
            conditional_factors[alias] = Factor(table_name, table_len, [key], pdf_1d,
                                                na_values=na_values)
        else:
            # 2 join keys: build 2D joint distribution via outer product (independence assumption) (raw counts)
            # outer[j,k] = pdf1[j]*pdf2[k]/fs, so that sum(outer) = fs (dimensionally consistent with 1D)
            key1, key2 = alias_keys[0], alias_keys[1]
            pdf1 = _get_pdf_for_key(key1, sp, gt_factor, table_name, table_buckets)
            pdf2 = _get_pdf_for_key(key2, sp, gt_factor, table_name, table_buckets)
            outer = np.outer(pdf1, pdf2)
            if fs > 0:
                outer = outer / fs
            conditional_factors[alias] = Factor(table_name, table_len, [key1, key2], outer,
                                                na_values=na_values)

    return conditional_factors


def get_ground_truth_no_filter(equivalent_keys, data, bins, table_lens, na_values):
    all_factor_pdfs = dict()
    for PK in equivalent_keys:
        bin_value = bins[PK]
        for key in equivalent_keys[PK]:
            table = key.split(".")[0]
            temp = apply_binning_to_data_value_count(bin_value, data[key])
            if table not in all_factor_pdfs:
                all_factor_pdfs[table] = dict()
            all_factor_pdfs[table][key] = temp / np.sum(temp)

    all_factors = dict()
    for table in all_factor_pdfs:
        all_factors[table] = Factor(table, table_lens[table], list(all_factor_pdfs[table].keys()),
                                    all_factor_pdfs[table], na_values=na_values[table])
    return all_factors
